# src/nlp/skill_list.py
"""A curated set of technical skill keywords and domain mappings for resume analysis."""

SKILL_SET = {
    # AI / LLM / Data Science
    "ai",
    "artificial intelligence",
    "ai engineer",
    "machine learning",
    "deep learning",
    "nlp",
    "natural language processing",
    "llama",
    "llama2",
    "qlora",
    "lora",
    "generative ai",
    "genai",
    "transformers",
    "huggingface",
    "fine-tuning",
    "prompt engineering",
    "rag",
    "vector database",
    "neural networks",
    "computer vision",
    "scikit-learn",
    "pytorch",
    "tensorflow",
    "keras",
    "opencv",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "data science",
    "data analysis",
    "data engineering",
    "data visualization",
    "big data",
    "spark",
    "hadoop",
    "etl",
    "statistics",
    "regression",
    "classification",
    "clustering",
    "reinforcement learning",
    "langchain",
    "llamaindex",
    "streamlit",

    # Core Programming Languages
    "python",
    "java",
    "c",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "sql",
    "nosql",
    "mongodb",
    "postgresql",
    "mysql",
    "go",
    "golang",
    "rust",
    "kotlin",
    "swift",
    "r",
    "scala",
    "ruby",
    "php",
    "dart",
    "matlab",

    # Cloud & DevOps & Infrastructure
    "aws",
    "azure",
    "gcp",
    "cloud computing",
    "cloud services",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "jenkins",
    "git",
    "github",
    "gitlab",
    "linux",
    "unix",
    "bash",
    "powershell",
    "ci/cd",
    "devops",
    "microservices",
    "rest api",
    "graphql",
    "nginx",
    "redis",
    "kafka",
    "rabbitmq",
    "elasticsearch",

    # Frameworks & Web
    "react",
    "angular",
    "vue",
    "nextjs",
    "nodejs",
    "django",
    "flask",
    "fastapi",
    "spring",
    "spring boot",
    "express",
    "html",
    "css",
    "sass",
    "bootstrap",
    "tailwindcss",
    "flutter",
    "react native",
    "svelte",

    # Computer Science Fundamentals
    "algorithm",
    "algorithms",
    "data structures",
    "software engineering",
    "full stack",
    "frontend",
    "backend",
    "system design",
    "software architecture",
    "oop",
    "agile",
    "scrum",
    "testing",
    "unit testing",
    "automation",
    "web scraping",
    "api development",

    # Cybersecurity & Networking
    "cybersecurity",
    "penetration testing",
    "network security",
    "encryption",
    "firewall",

    # Mobile
    "android",
    "ios",
    "mobile development",
}

# Domain canonical skill mapping to handle short role titles
# These represent skills a RECRUITER expects for the role
DOMAIN_SKILL_EXPANSION = {
    "ai engineer": {"python", "machine learning", "deep learning", "nlp", "transformers", "pytorch", "tensorflow", "algorithms", "neural networks", "data science"},
    "ai": {"python", "machine learning", "deep learning", "nlp", "data science"},
    "machine learning engineer": {"python", "machine learning", "deep learning", "scikit-learn", "pytorch", "tensorflow", "data science", "pandas", "numpy", "algorithms"},
    "ml engineer": {"python", "machine learning", "deep learning", "scikit-learn", "pytorch", "tensorflow", "data science", "pandas", "numpy"},
    "data scientist": {"python", "data science", "data analysis", "machine learning", "pandas", "numpy", "sql", "statistics", "data visualization"},
    "data analyst": {"python", "sql", "data analysis", "pandas", "data visualization", "statistics", "excel"},
    "data engineer": {"python", "sql", "etl", "data engineering", "spark", "hadoop", "big data", "aws"},
    "python developer": {"python", "django", "flask", "fastapi", "sql", "git", "docker", "rest api"},
    "full stack developer": {"javascript", "python", "react", "html", "css", "nodejs", "sql", "git", "rest api", "docker"},
    "full stack engineer": {"javascript", "python", "react", "html", "css", "nodejs", "sql", "git", "rest api", "docker"},
    "frontend developer": {"javascript", "react", "html", "css", "typescript", "git", "responsive design"},
    "frontend engineer": {"javascript", "react", "html", "css", "typescript", "git"},
    "react developer": {"react", "javascript", "typescript", "html", "css", "nodejs", "git", "rest api"},
    "backend developer": {"python", "java", "sql", "postgresql", "mongodb", "docker", "microservices", "rest api", "git"},
    "backend engineer": {"python", "java", "sql", "postgresql", "mongodb", "docker", "microservices", "rest api", "git"},
    "web developer": {"javascript", "html", "css", "react", "nodejs", "sql", "git", "rest api"},
    "software engineer": {"python", "java", "algorithms", "data structures", "git", "sql", "system design", "oop"},
    "software developer": {"python", "java", "algorithms", "data structures", "git", "sql", "oop"},
    "devops engineer": {"docker", "kubernetes", "terraform", "ci/cd", "aws", "linux", "bash", "git", "jenkins", "ansible"},
    "devops": {"docker", "kubernetes", "terraform", "ci/cd", "aws", "linux", "bash", "git"},
    "cloud engineer": {"aws", "azure", "gcp", "docker", "kubernetes", "terraform", "linux", "ci/cd"},
    "cloud architect": {"aws", "azure", "gcp", "docker", "kubernetes", "terraform", "system design", "microservices"},
    "mobile developer": {"android", "ios", "flutter", "react native", "dart", "kotlin", "swift", "git"},
    "android developer": {"android", "kotlin", "java", "git", "rest api", "sql"},
    "ios developer": {"ios", "swift", "git", "rest api"},
    "java developer": {"java", "spring", "spring boot", "sql", "git", "rest api", "docker", "microservices"},
    "nlp engineer": {"python", "nlp", "transformers", "pytorch", "tensorflow", "deep learning", "machine learning"},
    "deep learning engineer": {"python", "deep learning", "pytorch", "tensorflow", "neural networks", "computer vision", "nlp"},
    "generative ai engineer": {"python", "generative ai", "llama2", "transformers", "pytorch", "rag", "langchain", "prompt engineering"},
    "cybersecurity analyst": {"cybersecurity", "penetration testing", "network security", "linux", "python", "encryption"},
}

# Job-title words to filter from "missing skills" — these are role labels, not actual skills
JOB_TITLE_FILTER_WORDS = {
    "engineer", "developer", "analyst", "architect", "specialist",
    "manager", "lead", "senior", "junior", "intern", "associate",
    "consultant", "administrator", "designer", "officer", "executive",
}
